Chapter 4 Question 3 with Testing
careercup/CtCI-6th-Edition-Python pull request #111
Opened 2020-02-25 17:01 UTC by mertyertugrul

I added solution for Chapter 4 Question 3 with test cases using pytest and docstrings.
If it is accepted I like to add all question to to Chapter 4.
Additionally I had to update .gitignore file for VSCode and Virtual Environment files.

2020-12-04 16:28 UTC, brycedrennan requested changes
Thanks so much for your contribution here.  Especially like that you included tests. There are a few minor changes I'd request.

2020-12-04 16:28 UTC, brycedrennan commented on Chapter4/.vscode/settings.json
> +{
please remove this

2020-12-04 16:28 UTC, brycedrennan commented on Chapter4/43ListOfDepths/list_of_depths.py
> +if __name__ == "__main__":
this is unnecessary since it's doing nothing

2020-12-04 16:28 UTC, brycedrennan commented on Chapter4/43ListOfDepths/test_list_of_depths.py
> +from list_of_depths import *
let's move these files into the parent directory and not use a wildcard import

2020-12-20 20:14 UTC, brycedrennan commented
After looking at this again I see there was a misunderstanding. There should be a separate linked list for each depth.

I'll close this for now but happy to re-open later if you wish.

2020-12-20 20:17 UTC, mertyertugrul commented
I just noticed your comments, it has been a while since a made the request. Please re-open it I would like to contribute.

2020-12-20 20:21 UTC, brycedrennan commented
Great I'll reopen it. 

In the time since you submitted this, other work that was submitted earlier has been merged in and there are now existing solutions to this problem.  It might be easier to create a new pull request for any future work.

2020-12-20 20:24 UTC, mertyertugrul commented
Great thanks.

2020-12-24 05:58 UTC, brycedrennan commented
@mertyertugrul I'm going to close this for now.  I'll be happy to reopen if you make changes later. 

You are also welcome to open new pull requests with any new work you have.

2020-12-24 05:58 UTC, closed without merging