feature (ch05_p01): add easy-to-understand solution
careercup/CtCI-6th-Edition-Python pull request #163
Opened 2021-02-24 05:38 UTC by ryoyama0508

Added a solution `chapter_05/p01_insertion.py` since the original solution is a bit hard to read and understand for me. I hope this solution will be helpful for people in the same situation.

By the way, I personally think we should change the test cases because the question in the book says _"You are given two 32-bit __numbers__, N and M, and two bit positions, i and j. (question continues)"_. So I think test cases should be __numbers__(int), not string. My understanding might be weird or wrong since I'm not native speaker.

2021-02-24 06:07 UTC, ryoyama0508 commented
I changed my code since flake8 doesn't let me use `.format`.

2021-02-28 06:15 UTC, brycedrennan commented on chapter_05/p01_insertion.py
> +    return bin(int_n)[2:]
f-strings are the replacement for `.format` 

So you could do:
```python
 return f"{int_n:b}"
```

2021-02-28 06:15 UTC, brycedrennan commented on chapter_05/p01_insertion.py
> +    # change str into int in order to do bit manipulation
I agree that this should just be starting with integers.

2021-02-28 06:24 UTC, brycedrennan commented
Thanks! I just had some minor suggestions

2021-02-28 09:31 UTC, ryoyama0508 commented
Thanks for the suggestion. Changed the output to f-string. And also changed the input from string to integers. I wasn't sure what should I do to the other solution, so I just left it as it is.

2021-02-28 19:09 UTC, brycedrennan requested changes
Thanks for those updates. 

It's possible I'm mistaken but it seems this solution does not work if n is set to `int("11111111111", 2)` - the function outputs `11111111111`

Let me know what you think

2021-03-01 05:29 UTC, ryoyama0508 commented
> It's possible I'm mistaken but it seems this solution does not work if n is set to `int("11111111111", 2)` - the function outputs `11111111111`
> 
> Let me know what you think

I think you're completely right. I fixed that part.

Also, thanks for cleaning the test cases! Appreciate it.

2021-03-01 06:05 UTC, merged

2021-03-01 06:06 UTC, brycedrennan commented
Thanks - looks good!