feature(C17): added solutions
careercup/CtCI-6th-Edition-Python pull request #180
Opened 2021-03-18 14:47 UTC by rajatmodi62

Solutions added for :
p07
p08
p09
p13
p16
p17
p18
p21
p22

2021-03-19 03:42 UTC, brycedrennan commented
Do you want a code review or for us to cleanup the code? Either way is fine.

2021-03-19 04:46 UTC, rajatmodi62 commented
> Do you want a code review or for us to cleanup the code? Either way is fine.

Dear sir,
Many thanks for your reply. The code I have submitted works since I have already mentioned ctcis test cases there. 

Will be grateful if you could please cleanup the code. Meanwhile I will completely fill the gaps of this repo in terms of missing solutions on remaining hard and moderate problems
Thanks again

2021-03-23 06:27 UTC, brycedrennan commented on chapter_17/p08_circus_tower.py
> +a.sort(key= lambda x:-x[1])
all solutions should be in the form of a function

2021-03-23 06:27 UTC, brycedrennan commented on chapter_17/p21_volume_of_histogram.py
> +find_volume(hist)
any executing code should be wrapped in a `if __name__ == "__main__":`

2021-03-24 06:51 UTC, brycedrennan commented
I've merged your solution to C17_P07 here: https://github.com/careercup/CtCI-6th-Edition-Python/commit/9c1bdef2ab1fd0883ddf91928b1035ee5e99ecd2
and did this cleanup: https://github.com/careercup/CtCI-6th-Edition-Python/commit/b36cf146ba89eda9e0396161a1c9cd81855a7399

Will review other solutions later.

2021-03-24 16:12 UTC, brycedrennan commented
C17_P08 
merged: https://github.com/careercup/CtCI-6th-Edition-Python/commit/c60cbf4667b6c0e56c5eff9244d4c40e86b456d8
cleanup: https://github.com/careercup/CtCI-6th-Edition-Python/commit/0b6b20f79904d54704927d903111c5155d67dc13

2021-05-08 05:17 UTC, brycedrennan commented
C17_P09
merged: https://github.com/careercup/CtCI-6th-Edition-Python/pull/194/commits/eae90c5c3195aa18dc289e9116e76fd5d9a026fc
cleanup:  https://github.com/careercup/CtCI-6th-Edition-Python/pull/194/commits/584890e2240ff76c466646324130078d02ccd203

2021-05-08 06:01 UTC, brycedrennan requested changes
the solution to problem 13 doesn't appear to be correct

2021-05-08 06:01 UTC, brycedrennan commented
C17_P16
merged: https://github.com/careercup/CtCI-6th-Edition-Python/commit/ffca35842e27333287bcc28c4ee84ba7a683e2f6
cleanup: https://github.com/careercup/CtCI-6th-Edition-Python/commit/dde7f38bb3ac994563bac3268c39e27498230fd5

2021-05-08 06:13 UTC, brycedrennan commented
C17_P17
merged: https://github.com/careercup/CtCI-6th-Edition-Python/commit/49525a58bdca2cf726419ca98531d5c84fa990b5
cleaned: https://github.com/careercup/CtCI-6th-Edition-Python/commit/36e62dd091ac1ebd25e70db505ebf702f47b4a54

2021-05-08 06:28 UTC, brycedrennan commented
C17_P18
merged: https://github.com/careercup/CtCI-6th-Edition-Python/commit/c9f0cdbb4d5ace4e7870cd6406a00317d7f10dd5
cleaned: https://github.com/careercup/CtCI-6th-Edition-Python/commit/c9f0cdbb4d5ace4e7870cd6406a00317d7f10dd5

2021-05-08 06:51 UTC, brycedrennan commented
C17_P22
merged: https://github.com/careercup/CtCI-6th-Edition-Python/commit/46f26c76e73ec8fdebde57dabc89cf8b2ba626ce
cleanup: https://github.com/careercup/CtCI-6th-Edition-Python/commit/0dc648e7c4757e17af0e32b4e637d95b86521567

2021-05-08 06:52 UTC, brycedrennan commented
That takes care of this pull request. Please submit any future work in separate pull requests per solution.

2021-05-08 06:52 UTC, closed without merging